### ISSUE TITLE
Changes to project.yaml not being applied

### ISSUE THREAD

**Issue by johndwells** [fortrabbit/craft-auto-migrate#1]
I've just installed this for the first time (I'm trying out a FortRabbit app!), and have installed the plugin.  When I make a change that prompts a change to `project.yaml` (such as enable/disable a plugin), and then push the commit up, I _do_ see output from Auto Migrate which suggests it's successfully running the CLI commands, e.g. I see:

```
Composer:
  - - -
  Loading composer repositories with package information
  Installing dependencies (including require-dev) from lock file
  Nothing to install or update
  Generating optimized autoload files
  
  
  ▶ Craft auto migrate [START]
  Yii Migration Tool (based on Yii v2.0.16)
  
  Migrated up successfully.
  Applying changes from project.yaml ... done
  ▶ Craft auto migrate [END]
```

And yet, when I then visit my app in the browser, I'm still greeted with the "Changes to `project.yaml` must be applied to the loaded project config" message.

So I still end up having to either click that button or run `php craft project-config/sync` manually.

**Comment by ostark** [comment]
@johndwells Thanks this report as well. This is odd.
Can tell me the Craft version you are using?

**Comment by johndwells** [comment]
Ah sorry I should have mentioned that - Craft 3.1.14.

**Comment by ostark** [comment]
This composer plugin simply runs `craft project-config/sync` - even the output `Applying changes from project.yaml ... done` comes from Craft. So, the possible issue is not directly related to this package.

* Can you reproduce the issue? 
* Does the "button" always appears after you change the project.yml?
* Can you "fix" it by running `php craft project-config/sync` manually?

**Comment by johndwells** [comment]
So now I'm on my home machine trying again.  At the office I was doing `git push origin` (both from the terminal and via SourceTree), whereas now I opted to do via craft-copy and run `php craft copy/code/up`. And _this_ time, I still get an error but I also get an error output:

```
  ▶ Craft auto migrate [START]
  Yii Migration Tool (based on Yii v2.0.16)
  
  Migrated up successfully.
  Applying changes from project.yaml ... 
  error: Call to undefined method Symfony\Component\Process\Process::fromShellCommandline()
  
  ▶ Craft auto migrate [END]
```

And yes I can "fix" it by running `php craft project-config/sync`.

In fairness, I'll probably just resort to adding these commands to the post-install script of `composer.json`. But I'm kicking the tires of everything FortRabbit! :)

Thanks!

**Comment by jasonschock** [comment]
@ostark Seeing the same issue on a project with this plugin installed. I see output that it ran, but still had to apply Craft `project.yaml` updates via the browser button.

**Comment by jasonschock** [comment]
Or, as just now, I had to manually run `ssh myproject@deploy.us1.frbit.com php craft project-config/sync` even though logs from last deploy:
```  
  ▶ Craft auto migrate [START]
  Yii Migration Tool (based on Yii v2.0.16.1)
  
  Migrated up successfully.
  Applying changes from project.yaml ... done
  ▶ Craft auto migrate [END]
  ```

🤔

**Comment by ostark** [comment]
@jasonschock 
I had a look at the Craft core. The output of the `craft project-config/sync` command is not really useful. 
I can't imagine the issue is related to `fortrabbit/craft-auto-migrate`,  but it's worth digging a bit deeper.

**Comment by frank-laemmer** [comment]
Also likely related (or same issue):
https://github.com/fortrabbit/craft-copy/issues/38

**Comment by ostark** [comment]
@johndwells @jasonschock @frank-laemmer 
If you are using `fortrabbit/craft-auto-migrate` directly please give `2.0` a try, otherwise update `fortrabbit/craft-copy`.

**Comment by frank-laemmer** [comment]
Works for me.
