### ISSUE TITLE
Fatal error when running "composer install"

### ISSUE THREAD

**Issue by dommmel** [fortrabbit/craft-auto-migrate#2]
Hi there!

Thanks for the plugin. I started getting this error when running `composer install` in my local dev setup. Can't see where things get wrong at the moment. Any tipps?

Thanks again for open sourcing your work! 

```
Fatal error: Uncaught Error: Class 'Dotenv\Dotenv\Dotenv' not found in /home/docker/application/vendor/fortrabbit/craft-auto-migrate/src/Plugin.php:142
Stack trace:
#0 /home/docker/application/vendor/fortrabbit/craft-auto-migrate/src/Plugin.php(70): fortrabbit\CraftAutoMigrate\Plugin->bootstrapCraft()
#1 [internal function]: fortrabbit\CraftAutoMigrate\Plugin->runCommands(Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/Installer.php(324): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-install-cm...', true)
#5 phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Co in /home/docker/application/vendor/fortrabbit/craft-auto-migrate/src/Plugin.php on line 142

```

**Comment by ostark** [comment]
Strange `Dotenv\Dotenv\Dotenv` - that's not in the code.
Can you show `/home/docker/application/vendor/fortrabbit/craft-auto-migrate/src/Plugin.php` line 140-145

**Comment by dommmel** [comment]
Yes, indeed strange. Here's the code from that exact file:

```
138         // Load .env
139         if (file_exists($root . '/.env')) {
140             $dotenv = (method_exists('DotEnv\DotEnv', 'create'))
141                 ? DotEnv\DotEnv::create($root)
142                 : new Dotenv\Dotenv($root);
143             $dotenv->load();
144         }
145 
```

Thanks for looking into this!

**Comment by zimmermanj42** [comment]
I am also getting this same error trying to run a Composer install.

If I modify the "DotEnv\DotEnv" usages on lines 141 and 142 with just "DotEnv", it works.  I think there is something going on with how the namespace is being resolved.  At the top of the file, "DotEnv\DotEnv" is already getting imported.  I suppose then that when "DotEnv\DotEnv" is used later on, it tries to resolve "DotEnv\DotEnv\DotEnv".

Running PHP 7.2 myself if that is relevant.

**Comment by joshuabaker** [comment]
### Problem

It’s a typo.

In an older version [L12](https://github.com/fortrabbit/craft-auto-migrate/blob/e3825109cfa990d525feb1c6de2b57f85c97f7b4/src/Plugin.php#L12) uses the namespace `Dotenv\Dotenv`, which means that the `new Dotenv\Dotenv` on [L142](https://github.com/fortrabbit/craft-auto-migrate/blob/e3825109cfa990d525feb1c6de2b57f85c97f7b4/src/Plugin.php#L142) was trying to load `Dotenv\Dotenv` in `Dotenv\Dotenv` (i.e. `Dotenv\Dotenv\Dotenv`).

### Solution
Updating to [`v2.0.0`](https://github.com/fortrabbit/craft-auto-migrate/releases/tag/2.0.0) will solve this.

 `composer update` should work for most.

**Comment by ostark** [comment]
Thanks @joshuabaker
