### ISSUE TITLE
Remove config/project/* files

### ISSUE THREAD

**Issue by ostark** [fortrabbit/craft-auto-migrate#7]
Remove `config/project/*` files after applying project config successfully.
This should avoid confusion in production environments.

Craft will regenerate the entire folder structure from the database if `config/project/project.yaml` does not exist.

**Goal: avoid getting out of sync, especially when removing entryTypes/fields etc ...**

**Comment by ostark** [comment]
https://github.com/fortrabbit/craft-auto-migrate/commit/4d0d1a846ffb4282e55c1ee8f79ae2a70a247b03

**Comment by icreatestuff** [comment]
I'm not sure if this is related but every time I make a change locally that affects the project config files and deploy those to a production environment I always see the warning 'Your project config YAML files contain pending changes', as if the changes I have just applied haven't been applied. 

I can usually progress by manually checking and applying the changes through the project config utility page but it becomes more of an issue when plugins are removed and the project config on the production environment, for some reason, continues to expect them to be installed.

**Comment by howells** [comment]
Wonder if there's been any movement here - basically every project that uses this leaves the pending changes warning, which just confuses clients, some of whom want to go ahead and try to fix themselves. Any ideas?

**Comment by dgaidula** [comment]
see this for how to actually fix this problem, especially older installs that you are now bring under project config management.

https://github.com/fortrabbit/craft-auto-migrate/issues/12
